assignment1_pss/assignment1_pss/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    # Include prometheus metrics url
    path('', include('django_prometheus.urls')),
    # This will redirect / to /polls
    path('', RedirectView.as_view(pattern_name='polls:index')),
]

assignment1_pss/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('newquestion', views.QuestionView.as_view(), name='nuova_domanda'),
]

assignment1_pss/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

assignment1_pss/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django_prometheus.models import ExportModelOperationsMixin
from django.conf import settings


# Model for the questions
class Question(ExportModelOperationsMixin('question'), models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    # The question is created by a user
    created_by = models.ForeignKey(
      settings.AUTH_USER_MODEL,
      on_delete=models.CASCADE
    )

    def __str__(self):
        return self.question_text

    # Check if the question was published within 24 hours
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


# Model for the choices
class Choice(ExportModelOperationsMixin('choice'), models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

assignment1_pss/users/models.py
from django.contrib.auth.models import AbstractUser
from django_prometheus.models import ExportModelOperationsMixin


# Extends the basic django user authentication
class CustomUser(ExportModelOperationsMixin('user'), AbstractUser):

    def __str__(self):
        return self.get_username()

assignment1_pss/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

assignment1_pss/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from braces.views import LoginRequiredMixin
from .models import Choice, Question
from django.utils import timezone


# Shows all questions available
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')


# LoginRequiredMixin blocks access to views to unregistered users
# Shows all the choices available for a specific question
class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = '/polls'
    model = Question
    template_name = 'polls/detail.html'


# Shows the voting results for a specific question
class ResultsView(LoginRequiredMixin, generic.DetailView):
    login_url = '/polls'
    model = Question
    template_name = 'polls/results.html'


# Allows registered users to create new questions
class QuestionView(LoginRequiredMixin, generic.TemplateView):
    login_url = '/polls'
    template_name = 'polls/newquestion.html'

    def post(self, request, *args, **kwargs):
        return create_new_question(request)


# Add a new question and its relative choices into db
def create_new_question(request):
    question = request.POST['question']
    answers = request.POST['answer']

    if question != '' and answers != '':
        q = Question(question_text=question,
                     pub_date=timezone.now(),
                     created_by=request.user)

        q.save()

        for answer in reversed(answers.split(',')):
            q.choice_set.create(choice_text=answer,
                                votes=0)

        return HttpResponseRedirect(reverse('polls:index'))
    else:
        return render(request, 'polls/newquestion.html', {
            'error_message': "La domanda non può essere vuota",
        })


# Vote for the question specified by question_id
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

assignment1_pss/users/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm


# Allows the registration of new users
class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

assignment1_pss/polls/templates/polls/detail.html
{% extends 'users/base.html' %}

{% block title %} Dettaglio domanda {% endblock %}

{% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
<br>
<form>
    <button formaction="{% url 'polls:index' %}">Home</button>
</form>
{% endblock %}

assignment1_pss/polls/templates/polls/index.html
{% extends 'users/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

{% if user.is_authenticated %}
Ciao {{ user.username }}! <a href="{% url 'logout' %}">logout</a>
<br><br>
<a id="id_newquestion" href="{% url 'polls:nuova_domanda' %}">Inserisci una domanda</a>

<h2>Domande disponibili</h2>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        [{{ question.created_by}}]
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

{% else %}
<p>Devi essere autenticato per visualizzare le domande</p>
<a href="{% url 'login' %}">login</a>
{% endif %}

{% endblock %}

assignment1_pss/polls/templates/polls/newquestion.html
{% extends 'users/base.html' %}

{% block title %} Nuova domanda {% endblock %}

{% block content %}
<h2>Nuova domanda</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post" action="#">
    {% csrf_token %}
    Titolo della domanda
    <br>
    <input type="text" id="id_question" name="question">
    <br>
    Inserisci le risposte della domanda separate da virgola
    <br>
    <textarea id="id_answers" style="resize:none" rows="4" cols="50"
              placeholder="opzione1,opzione2,..." name="answer"></textarea>
    <br>
    <button id="id_submit" type="submit">Crea domanda</button>
</form>
<br>
<form>
    <button formaction="{% url 'polls:index' %}">Home</button>
</form>
{% endblock %}

assignment1_pss/polls/templates/polls/results.html
{% extends 'users/base.html' %}

{% block title %} Risultati {% endblock %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<br>
<br>
<form>
    <button formaction="{% url 'polls:index' %}">Home</button>
</form>

{% endblock %}

assignment1_pss/users/templates/users/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %} Title {% endblock %}</title>
</head>
<body>
<main>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

assignment1_pss/users/templates/users/home.html
{% extends 'users/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}!
<p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">login</a> |
<a href="{% url 'signup' %}">signup</a>
{% endif %}
{% endblock %}

assignment1_pss/users/templates/users/signup.html
{% extends 'users/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button id="id_submit" type="submit">Sign up</button>
</form>
<br>
<form>
    <button formaction="{% url 'polls:index' %}">Home</button>
</form>
{% endblock %}